Bug 1119228 - Fix a fatal warning in PossiblyFail; r=jandem
Recent clang emits the following warning (which is treated as an error) on this code:
error: implicit conversion of nullptr constant to 'bool' [-Werror,-Wnull-conversion]

UltraBlame original commit: bcacb5692ad902fc0ec6ebea2ad382a8a3fd5183