Bug 1117772 - Return false from PluginInstanceParent::CreateBackground; r=baku
clang emits the following warning on this code, which is treated as an
error:
error: implicit conversion of nullptr constant to 'bool' [-Werror,-Wnull-conversion]

UltraBlame original commit: 69c16464fa30692f095e07c727c3aa1f6472a682