Backed out changeset 7819e11aa46f, bug 592052 because of Mac OS X build bustage:
Undefined symbols:
  "_NSGetModule", referenced from:
     -exported_symbols_list command line option
ld: symbol(s) not found

UltraBlame original commit: 9338043ef10de4db97df09334ccfcf0e5961e50f