Bug 1122781 part 1 - Declare and statically check dependencies of style structs. r=dbaron
When a cyclic dependency is introduced, build will stop at generating style struct list.
For example, if you make Visibility depend on Font while Font also depend on Visibility, it would print lines like:

ERROR: Cannot resolve style struct dependencies
Resolved items: Variables Color Quotes UserInterface UIReset Table XUL
There exist cyclic dependencies in the following structs: Font List Text Visibility TableBorder SVG Background Position TextReset Display Content Margin Padding Border Outline SVGReset Column

UltraBlame original commit: 7eb2c4dc10f2f0bdd6d60e00ded65ca1966651bd