Back out changeset 9dce1a90205e (bug 1139657) for B2G emulator xpcshell test failures.
Since this landed, every B2G ICS emulator opt xpcshell run has failed with:
TEST-UNEXPECTED-TIMEOUT | services/fxaccounts/tests/xpcshell/test_accounts.js | Test timed out
DMError: Timeout exceeded for shell call

UltraBlame original commit: cf60b84ee25882958cca70ce59603efbfca96a89