Bug 1135535 part 3 - Fix C4258 definition ignored warnings and mark it an error in js/src on MSVC. r=luke
Fix warnings:
js\src\vm/UnboxedObject.cpp(212) : error C4258: 'i' : definition from the for loop is ignored; the definition from the enclosing scope is used
        js\src\vm/UnboxedObject.cpp(209) : definition of 'i' ignored
        js\src\vm/UnboxedObject.cpp(204) : definition of 'i' used
js\src\vm/UnboxedObject.cpp(213) : error C4258: 'i' : definition from the for loop is ignored; the definition from the enclosing scope is used
        js\src\vm/UnboxedObject.cpp(209) : definition of 'i' ignored
        js\src\vm/UnboxedObject.cpp(204) : definition of 'i' used

UltraBlame original commit: 3ae7642fc71b05acaf2d062e7199bee290f511f3