Bug 1092587 - TypeError: Promise.defer is not a function, causing browser chrome failures. r=Yoric
UltraBlame original commit: ebb8c73555a128ae7e3d4723254bfde7ef27dce4